apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: mongo
      hasuraService: custom
    name: mongo
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mongo
      spec:
        containers:
        - image: mongo:latest
          imagePullPolicy: IfNotPresent
          name: mongo
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
          - name: MONGO_INITDB_DATABASE
            value: test
          volumeMounts:
          - name: mongo-pv
            mountPath: /data/db
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
        volumes:
        - hostPath: 
            path: /data/mongo
          name: mongo-pv
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: mongo
      hasuraService: custom
    name: mongo
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongo
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
